"""
Resolve an item id (or item-stack dict) to its inventory **icon** file.

Icons are generated by :mod:`game.tools.make_item_icons` into
``assets/sprites/items/<id>.png`` with per-category fallbacks
(``_weapon.png``, ``_armour.png``, …). This module is the single lookup both
the editor's grid inventory and the in-game inventory screen use, so a modded
item with no bespoke icon still gets a sensible category glyph.

Pure-path logic (no Qt) plus an optional cached ``icon_pixmap`` helper that is
only imported where PyQt5 is present.
"""

from __future__ import annotations

import os
from functools import lru_cache
from typing import Optional

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
_ICON_DIR = os.path.join(_ROOT, "assets", "sprites", "items")

# id -> category, loaded lazily from the item DB so fallbacks stay accurate.
_CATEGORY_CACHE: Optional[dict] = None


def _categories() -> dict:
    global _CATEGORY_CACHE
    if _CATEGORY_CACHE is None:
        _CATEGORY_CACHE = {}
        try:
            import json
            with open(os.path.join(_ROOT, "game", "data", "items.json"), encoding="utf-8") as f:
                db = json.load(f)
            for iid, rec in db.items():
                _CATEGORY_CACHE[iid] = str(rec.get("category", "")).lower()
        except Exception:
            _CATEGORY_CACHE = {}
    return _CATEGORY_CACHE


def _category_of(stack) -> str:
    if isinstance(stack, dict):
        for key in ("category", "type", "slot"):
            v = stack.get(key)
            if v:
                return str(v).lower()
    return ""


def icon_path(item_id, stack=None) -> Optional[str]:
    """Absolute path to the best icon for *item_id* / *stack*, or None.

    Tries the exact id, then the item's category fallback (``_weapon.png`` …),
    then a generic ``_misc.png``. ``stack`` (the item dict) is optional and only
    used to recover a category when the id is unknown to the DB."""
    iid = str(item_id or "")
    exact = os.path.join(_ICON_DIR, f"{iid}.png")
    if os.path.isfile(exact):
        return exact
    cat = _category_of(stack) or _categories().get(iid, "")
    # normalise a couple of synonyms to the files we actually ship
    cat = {"armor": "armour", "consumable": "potion", "key": "misc",
           "quest": "misc"}.get(cat, cat)
    if cat:
        fb = os.path.join(_ICON_DIR, f"_{cat}.png")
        if os.path.isfile(fb):
            return fb
    generic = os.path.join(_ICON_DIR, "_misc.png")
    return generic if os.path.isfile(generic) else None


# ---------------------------------------------------------------------------
# Qt convenience (imported only where PyQt5 exists).
# ---------------------------------------------------------------------------
@lru_cache(maxsize=256)
def _load_pixmap(path, size):
    from PyQt5.QtGui import QPixmap
    from PyQt5.QtCore import Qt
    pm = QPixmap(path)
    if pm.isNull():
        return None
    if size:
        pm = pm.scaled(size, size, Qt.KeepAspectRatio, Qt.SmoothTransformation)
    return pm


def icon_pixmap(item_id, stack=None, size: int = 48):
    """A cached ``QPixmap`` for the item, scaled to *size*, or None."""
    path = icon_path(item_id, stack)
    if not path:
        return None
    try:
        return _load_pixmap(path, int(size))
    except Exception:
        return None


def icon(item_id, stack=None, size: int = 48):
    """A cached ``QIcon`` for the item (empty QIcon if nothing resolves)."""
    from PyQt5.QtGui import QIcon
    pm = icon_pixmap(item_id, stack, size)
    return QIcon(pm) if pm is not None else QIcon()
